all: random

random: random.c
	# gcc sobel.c -o sobel -lm
	gcc -Wall -Werror -ggdb2 random.c -o random

color: color.c
	gcc -Wall -Werror -ggdb2 color.c -o color

clean:
	rm -rf random *.dSYM .DS_Store color